name: Deploy to WordPress.org Repository

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@2.3.0
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_WP_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_WP_PASSWORD }}
        SLUG: ${{ secrets.PLUGIN_WP_SLUG }}
